### ISSUE TITLE
Screenshots are affected

### ISSUE THREAD

**Issue by Josjs** [F-i-f/soft-brightness#1]
When print-screening or using the gnome-screenshot app, the darkening is captured making the screenshot look dark as seen in the attached image.
![Screenshot](https://user-images.githubusercontent.com/6876510/55621474-e1b92500-579d-11e9-8ff2-b09fbdd81467.png)

Worth noting that window-capture produces unaffected screenshots.

**Comment by F-i-f** [comment]
Unfortunately, there's not much that can be done, except turning the brightness back on to the max for the screen shot process.
I'll see if I can briefly turn off the overlay for the screen shot, but don't count on it.  This would only work for gnome-shell screenshots, but third-party apps would probably still see the overlay.

**Comment by F-i-f** [comment]
Please try:
[soft-brightness@fifi.org-v7-2-g5bae0e6.zip](https://github.com/F-i-f/soft-brightness/files/3066705/soft-brightness%40fifi.org-v7-2-g5bae0e6.zip)

Just unzip it under `~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org` and overwrite the files that are in there.

The brightness overlay should now be removed when performing screenshots (desktop & area) with Gnome-Shell.

It is impossible to detect 3rd-party screenshot applications and remove the overlay when they take screenshots, but at least this will work with gnome-shell screenshots.

**Comment by F-i-f** [comment]
I have release version 8 which fixes the problem.
It's currently under review by the gnome-shell team.
In meantime you can get it from the [project homepage](https://github.com/F-i-f/soft-brightness/) or download [version 8 directly here](https://github.com/F-i-f/soft-brightness/releases/download/v8/soft-brightness@fifi.org.v8.shell-extension.zip).

**Comment by Josjs** [comment]
Works great, thank you!
