### ISSUE TITLE
Not working in Gnome 3.36

### ISSUE THREAD

**Issue by mattemc** [F-i-f/soft-brightness#12]
Extension version: 18
Gnome-shell version: 3.35.91
Mutter version: 3.35.91-1ubuntu1
on Ubuntu 20.04
I tried installing the latest version of the program in 3 different ways:
Through the Gnome extensions wab application
By downloading the latest release (v18) from the gitHub repository and placing it in ~/.local/share/gnome-shell
and by cloning the repository with git `git clone https://github.com/F-i-f/soft-brightness.git ~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org
`
In none of the cases the icon is displayed in the tray bar, the extension is not listed in Extensions of Ubuntu. The application is listed in gnome tweaks but it's not possible to toggle it on, also accessing to the configuration panel is impossible.

**Comment by F-i-f** [comment]
Can you try upgrading to Gnome-Shell 3.36?
3.35.91 is a development version and is not supported.

**Comment by F-i-f** [comment]
I have multiple reports that the extension is working with 3.36.
Have you had a chance to update gnome-shell to a supported version?

**Comment by F-i-f** [comment]
Closing this issue since the reporter is unresponsive.
