### ISSUE TITLE
Mouse pointer lag or not update when hover on links or textbox

### ISSUE THREAD

**Issue by meepeek** [F-i-f/soft-brightness#13]
problem found in gnome wayland but not in X

1. in chromium when hover on links or textbox, the cursor rarely change, e.g. not change from pointerto i-beam or hand and when it changed, it will rarely change to others.
2. in wine game civ2 cursor affected as well.

seems [this extension](https://extensions.gnome.org/extension/1130/dim-desktop-70/) have a solution.

**Comment by F-i-f** [comment]
Sadly it's a known issue, see #5.
The extension you're citing sidesteps the problem by not changing the brightness of the cursor at all, while Soft Brightness attempts to do so, and somewhat fails at it.
