### ISSUE TITLE
Gnome 3.38 issue

### ISSUE THREAD

**Issue by tomWhilbert** [F-i-f/soft-brightness#16]
When I enable `soft-brightness` in 3.38.1 the mouse cursor disappears. 
Arch 5.4

Thanks

**Comment by dlyr** [comment]
confirmed here, the cursor disappears only after screen saver/screen lock.
I had reset all my gnome settings to default, and find soft-brightness extension is causing the issue while I was reconfiguring.
By the way great and useful extension.

**Comment by F-i-f** [comment]
Thanks for the report.
Sadly, it's a Gnome Shell (probably gjs) issue as explained in https://github.com/F-i-f/soft-brightness#known-issues-with-gnome-shell-338
There's a new release out (v20) that works around the problem.  It may take a little bit for the extension to get approved, but in the meantime, you can always disable _Mouse cursor brightness control_ in the extension's settings.

**Comment by rmeissn** [comment]
I am using Fedora 33 with Gnome 3.38.1 and gjs 1.66.1-2. In case I enable the mouse cursor brightness control within soft-brightness, my cursor disappears randomly (e.g. on brightness change). I got the latest release of soft-brightness and the bug reports (linked in the readme) are both resolved, but I still have this issue.

**Comment by F-i-f** [comment]
@rmeissn What's your Soft Brightness version (Gnome Tweaks > Extensions > Soft Brightness (gear icon))?
The only working versions on GS 3.38 are v20 (no mouse cursor brightness control) and v25 (working mouse cursor brightness control).  All the others are broken (and have been withdrawn).

If you don't have v25, please upgrade to that version.  It was approved about 12h ago.

**Comment by rmeissn** [comment]
My current version is v25/ git v25-0-g1031dba
I'm not sure whether v24 or v25 was active yesterday. Today I tested a bit and the above described issue seems gone when booting my Laptop without having it connected to an external monitor. It also works fine if connecting it to the external monitor (via HDMI over USB-C) after booting it. In the latter case I noticed a little cursor offset (one char to the right, half one down), which isn't there in the following case.
When booting with the external monitor connected, the cursor has a different brightness (brighter) than the whole display and is stuck after a few seconds. I can still move the cursor, click things and so on, but the cursor is mostly invisible and rendered to a fixed position (in correct brightness). The actual cursor appears for a second if I press ESC, but not in every view and is brighter than it should be. This behaviour is gone when I disable cursor brightness control, but then the cursor is (obviously) too bright. This is reproducible over reboots.
I've uploaded a video, showcasing the second case. You can even see the cursor brightness differences. https://files.iis.aksw.org/s/e7qoRGF9aejQ7LC

I'll happily provide journal logs if you tell me what I should filter for.

**Comment by F-i-f** [comment]
That's odd.

Please enable debugging in the extension settings.

Then log out and log in (or restart gnome-shell, if you can, with _ALT-F2 r_ (this won't work on Wayland, you have to log out and log back in), reproduce the issue, then attach the output of `journalctl -b | grep gnome-shell` to this report.

Thanks.

**Comment by rmeissn** [comment]
I tested again today and still got the same issue with v26. Here is the required log (restarted the system with enabled debug option):

[log.txt](https://github.com/F-i-f/soft-brightness/files/5994854/log.txt)
