### ISSUE TITLE
Doesn't install properly on Ubuntu 20.04 / Gnome 3.36.3

### ISSUE THREAD

**Issue by DarkPhoenix645** [F-i-f/soft-brightness#17]
This extension was working great until I tried to install the most recent update from the [Gnome Extensions Page](https://extensions.gnome.org/extension/1625/soft-brightness/) this morning. 
After I tried to install it, I got an error. Hoping this was an installation problem and not a problem with the extension (I love this extension as the built-in brightness control doesn't work), I tried to install it myself using the instructions on the [Github page](https://github.com/F-i-f/soft-brightness/) but I got the following error: 

The settings of extension soft-brightness@fifi.org had an error:
```
Error: Schema org.gnome.shell.extensions.soft-brightness could not be found for extension soft-brightness@fifi.org. Please check your installation.
```

Stack trace:
```
getSettings@/home/nilanjan/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/convenience.js:88:15
setup@/home/nilanjan/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/prefs.js:43:31
buildPrefsWidget@/home/nilanjan/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/prefs.js:240:12
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by DarkPhoenix645** [comment]
Resolved!
I don't know how this happened but I tried installing it again manually, but this time I unpacked and built it in the `home` directory and then moved it to ```~.local > share > gnome-shell > extensions``` and it worked.

**Comment by F-i-f** [comment]
Happy to hear all is fine.

**Comment by DarkPhoenix645** [comment]
Thank you for your great work once again!
