### ISSUE TITLE
The base brightness went very low

### ISSUE THREAD

**Issue by MoDotEu** [F-i-f/soft-brightness#18]
The 100% brightness for the gnome is not 100% any more.
I mentioned that, because switching to mate or creating another user  and login to gnome has the expected brightness.
disabling or even removing, reinstalling the extension didn't help at all.
i help myself buy increasing the brightness with xrandr using sth. like

`xrandr --output DVI-D-0 --brightness 2.5`

But this is 100% incorrect, because making a screenshot of the monitor shows the problem clear.
I guess another value is somewhere changed, that i cant find. i investigated all values in dconf-editor without any success.

I hope anybody has an idea how to solve this problem. 
Thanks in advance

**Comment by F-i-f** [comment]
Does the brightness go back to 100% if the extension is disabled or removed?

Are you sure there's not something else changing the display?  Something like Gnome Night Light, the color profiles, or direct xrandr manipulation?

**Comment by F-i-f** [comment]
Closing this issue because of lack of feedback.
