### ISSUE TITLE
Uses 10-20% of CPU, even when brightness is set at 100%

### ISSUE THREAD

**Issue by inferont** [F-i-f/soft-brightness#19]
The overlay seems to still exist even when the brightness slider is all the way up. Since this extension uses around 10-20% of my CPU I have to disable the extension completely. Fixing this should be as simple as turning off the overlay code when brightness is at 100%.

**Comment by F-i-f** [comment]
The overlays are already removed when the brightness level is at 100%:
https://github.com/F-i-f/soft-brightness/blob/71153231d40ed2b669b6ec93bbfbedc89f953d73/src/extension.js#L536

I'm sorry to hear that the CPU usage, but there's not much that can be done about it.

Have you tried disabling mouse tracking?  That should improve CPU/power usage.

**Comment by F-i-f** [comment]
Closing this issue.
