### ISSUE TITLE
docs - note how this affects battery life

### ISSUE THREAD

**Issue by javenschuetz** [F-i-f/soft-brightness#2]
Hi,

This extensions performs as described and softens the brightness. However, this is done via both 'backlight' and 'alpha' tuning. Since the major reason a person would dim their screen is to preserve battery, it would be helpful to add a note to clarify how this combination can be interpreted in terms of battery life.

For example, after installing this and enabling backlight control, I am able to set my brightness bar is at approx half. The screen is dimmer than before at very low brightness, but I am not sure if I am using more or less battery than I was before due to the alpha/backlight interaction.

**Comment by F-i-f** [comment]
Thank your for your suggestion.
I've added a [section about power consumption](https://github.com/F-i-f/soft-brightness#effect-on-power-consumption) to `README.md`.
Please reopen the bug if you feel the documentation is still lacking.
