### ISSUE TITLE
Mouse offset

### ISSUE THREAD

**Issue by apelloni** [F-i-f/soft-brightness#20]
I'm using arch with gnome 3.38.1 and I had to remove this extension since it was rendering the mouse with an offset.

from my journal 
```
Oct 24 13:13:10 gnome-shell[684]: JS ERROR: TypeError: this._cursorSprite.set_anchor_point is not a function
                                        _updateMouseSprite@/home/andrea/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/extension.js:795:21
```

When I was clicking with the right or middle button of the mouse I could see two cursors.
The first was the one processed by the extension and showed a dimmed color while the second was brighter.
The bright one was correctly positioned and disappeared as soon as I moved the mouse.

**Comment by F-i-f** [comment]
Thanks for your bug report.

Fixed in release v22.
