### ISSUE TITLE
mouse cursor click zone shifted

### ISSUE THREAD

**Issue by gyan000** [F-i-f/soft-brightness#25]
Hello,

There's a weird issue with Gnome 3.38 (tested on Fedora 33 / Gnome 20.10).

When the extension's option "Mouse cursor brightness control." is activated the mouse cursor zone which is used to know where you click is slightly shifted to  10\~15px on the top-left.

[Here a video showing the issue](https://framadrop.org/lufi/r/U14pZWee9A#TmuDpe7J+Wa2tessZfEwR6itwG+xBWn3TO/hkf+NZ6s=)

Log that after having recorded the video, the issue really appears in the way that you will see, in the first part of the video when the option is activated, the mouse cursor duplicated - and where the real cursor is the one which is right-bottom shifted.

Deactivating the option fix this issue; and the extension works as expected, so it's not critical at all, but I still wanted to mention it. And maybe this issue is not specific to this extension, probably a more general issue somewhere in system library... I don't know.

Thanks.

**Comment by F-i-f** [comment]
Thanks for the bug report.

I can reproduce the issue, although not all the time.  Something must have changed (again) in the cursor handling.

In the meantime, you can disable "Mouse cursor brightness control".

**Comment by F-i-f** [comment]
Fixed in version 26.
Until it's approved by Gnome, you can manually download and install it from [here](https://github.com/F-i-f/soft-brightness/releases/download/v26/soft-brightness@fifi.org.v26.shell-extension.zip).
