### ISSUE TITLE
Overlay covers mouse

### ISSUE THREAD

**Issue by Tiamarth** [F-i-f/soft-brightness#3]
Recent update from Gnome Extensions causes the mouse to disappear when the overlay is activated by decreasing the brightness. Installed manually from git, same issue. I assume it's because the overlay is now covering the mouse where previously it was under the mouse.

Gnome 3.32.1

**Comment by F-i-f** [comment]
Confirmed it's a bug.

Please try:
[soft-brightness@fifi.org-v9-4-gfc854e8.zip](https://github.com/F-i-f/soft-brightness/files/3106604/soft-brightness%40fifi.org-v9-4-gfc854e8.zip)

Just unzip it under `~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org` and overwrite the files that are in there.
It should work now.

**Comment by Tiamarth** [comment]
Thanks! The update does solve this issue.

**Comment by F-i-f** [comment]
Thank you for your confirmation.
I've released the extension version 10 which fixes this problem and a few other corner cases with the cursor brightness.
It's currently under review by the gnome-shell team.
In meantime you can get it from the [project homepage](https://github.com/F-i-f/soft-brightness/) or download [version 10 directly here](https://github.com/F-i-f/soft-brightness/releases/download/v10/soft-brightness@fifi.org.v10.shell-extension.zip).

**Comment by Tiamarth** [comment]
Thanks again, I now have it installed. Another, possibly related issue, is that I can't drag and drop windows from one workspace to another in the overview when the overlay is enabled by decreasing the brightness. Should I create another issue for this new problem or just keep it here?

**Comment by F-i-f** [comment]
Please create a new issue.
Thanks,
