### ISSUE TITLE
No Schema Found

### ISSUE THREAD

**Issue by mroovaa** [F-i-f/soft-brightness#32]
Hello and thank you for this great extension.

Could you please provide schema to it?

This way particular brightness settings could be easily bound to keyboard shortcuts with e.g:

gsettings set org.gnome.shell.extensions.soft-brightness current-brightness 0.6

All the Best.

**Comment by F-i-f** [comment]
The extension's schema is available either in:
- `/usr/share/gnome-shell/extensions/soft-brightness@fifi.org/schemas/org.gnome.shell.extensions.soft-brightness.gschema.xml` (system-installed)
    or
- `~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/schemas/org.gnome.shell.extensions.soft-brightness.gschema.xml` (user-installed)

For some reason, `gsettings` cannot set gnome-shell extensions' settings.  I do not think it's limited to the Soft Brightness extension.  You should report the bug to gnome.
You can still use `dconf` directly to read or write the Soft Brightness settings:
```shell
% dconf read /org/gnome/shell/extensions/soft-brightness/current-brightness 
0.63798689277251186
% dconf write /org/gnome/shell/extensions/soft-brightness/current-brightness 0.2
% dconf write /org/gnome/shell/extensions/soft-brightness/current-brightness 0.65
```
