### ISSUE TITLE
gnome 40 support?

### ISSUE THREAD

**Issue by fastrizwaan** [F-i-f/soft-brightness#34]
This is one of the most important extensions I use, include clipboard indicator, and shutdown timer.
Kindly make soft-brightness work with gnome 40 (fedora 34). Thanks.

**Comment by F-i-f** [comment]
Duplicate of #33, and already [fixed](https://github.com/F-i-f/soft-brightness/releases/download/v27/soft-brightness@fifi.org.v27.shell-extension.zip) with some [caveats](https://github.com/F-i-f/soft-brightness#known-issues-with-gnome-shell-400).
