### ISSUE TITLE
VSync won't go past 60Hz on HRR monitors

### ISSUE THREAD

**Issue by ethanrushh** [F-i-f/soft-brightness#43]
For users with a non-60Hz monitor, when the brightness is not 100% (thus the extension is actively being used) the screen will act as though it is running at 60Hz, presumably from the VSync. This is unexpected and unintended behaviour, so I have opened up an issue for it.

HRR standing for High Refresh Rate.

**Comment by F-i-f** [comment]
This extension unfortunately requires having Gnome Shell managing the screen rendering (otherwise no alpha overlay), and Gnome Shell requires or set VSync.
It is normal that you'd see this behavior and there's nothing that a Gnome Shell extension can do.
Please redirect your issue to Gnome Shell.
