### ISSUE TITLE
Mouse Coursor invisible after login

### ISSUE THREAD

**Issue by kindlydodo** [F-i-f/soft-brightness#45]
- I am using Extension Version 27, default settings
- My System: $ uname  -a
Linux pc-021 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

After the first login into Gnome, the Cursor are not visible. I have to change the Brightness in the Extension, then the Cursor shows up.

**Comment by kindlydodo** [comment]
I have set on the Exension Option "Use backlight control" and it seems that this resolve the issue

**Comment by kindlydodo** [comment]
this issue is not solved

**Comment by F-i-f** [comment]
Can you try version 28?
If it still fails, please send a log:
- Enable Debug in the extension's settings.
- Disable all extensions but Soft Brightness.
- Logout.
- Log back in.
- Send the output of `journalctl -S '5 minutes ago'`.

**Comment by kindlydodo** [comment]
Here is just another log from this problem. Hope it helps.

[log.txt](https://github.com/F-i-f/soft-brightness/files/7874866/log.txt)

**Comment by F-i-f** [comment]
[Release 30](https://github.com/F-i-f/soft-brightness/releases/tag/v30) is just out and contains fixes related to cursor handling.
Would you mind trying it out and reporting back if it works?

**Comment by kindlydodo** [comment]
hi F-i-f

Since the update, and restore the extension to default, in never faced the issue again. Good job, thanks!
