### ISSUE TITLE
Mouse Coursor invisible after login

### ISSUE THREAD

**Issue by kindlydodo** [F-i-f/soft-brightness#48]
sorry i accidentally closed this issue (https://github.com/F-i-f/soft-brightness/issues/45). The problem persists:

- I am using Extension Version 27, default settings
- My System: $ uname  -a
Linux pc-021 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

After the first login into Gnome, the Cursor are not visible. I have to change the Brightness in the Extension, then the Cursor shows up.

**Comment by F-i-f** [comment]
Please try version 28.

If it still fails, could you capture a log:
- Enable Debug in the extension's settings.
- Disable all extensions but Soft Brightness.
- Logout.
- Log back in.
- Send the output of `journalctl -S '5 minutes ago'`.

**Comment by F-i-f** [comment]
This is a duplicate ot #45.
