### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by Lcchy** [F-i-f/soft-brightness#51]
Thanks a lot for the great extension first of all!
I tried to port the extension manually to Gnome 42 (on Fedora 36) for testing but it seems to cause some wild flickering of the cursor
and the screen.
I don't have the knowledge to debug it but I'd be happy to provide debug logs etc

**Comment by Darukutsu** [comment]
For a period you should be able to fix it by disabling: "Mouse cursor brightness control". At least this works for my arch setup.

**Comment by Lcchy** [comment]
It worked! Thanks for the workaround

**Comment by EuriNaiz** [comment]
Hi @Lcchy, Can you share the port with me? or even better, if you can, send a PR plz.

**Comment by Lcchy** [comment]
Hi, the temporary fix is just to go in the settings of the extension and uncheck "Mouse cursor brightness control".
But first you need to allow the extension to run in Gnome 42 by adding  "42" to `"shell-version"` in the file `~/.local/share/gnome-shell/extensions/soft-brightness@fifi.org/metadata.json`.
This cannot be a PR as its just a workaround, not a real fix

**Comment by F-i-f** [comment]
Full Gnome 42 support is in [release 30](https://github.com/F-i-f/soft-brightness/releases/tag/v30).
