### ISSUE TITLE
screenshots getting affected by brightness setting

### ISSUE THREAD

**Issue by sp8996** [F-i-f/soft-brightness#52]
I am using **opensuse tumbleweed** (**gnome 42**) with **latest version of soft-brightness** and **screenshots get affected by brightness settings**. I am also attaching screenshots at two different bightness level for comparison
![Screenshot from 2022-05-03 10-24-53](https://user-images.githubusercontent.com/58138197/166406377-335b6091-f1e1-4744-8ff6-137d229ef59f.png)
![Screenshot from 2022-05-03 10-26-41](https://user-images.githubusercontent.com/58138197/166406381-4f982838-b590-48c4-af83-7bdc12845052.png)
.

**Comment by F-i-f** [comment]
Fixed in [release 30](https://github.com/F-i-f/soft-brightness/releases/tag/v30).
The screenshot handling wasn't working, that why Soft Brightness didn't officially support Gnome 42 yet.

**Comment by azzamsa** [comment]
related: https://github.com/flameshot-org/flameshot/issues/2547

I believe video recording is also affected.
