### ISSUE TITLE
Gnome 3.34 compatibility

### ISSUE THREAD

**Issue by tommy4st** [F-i-f/soft-brightness#6]
When enabling this extension all applications become unresponsive to mouse events. Gnome Shell itself is working, that means I can log out or open new applications, but I cannot interact with any application using the mouse. Keyboard inputs still work. That's how I deactivate all extensions by issuing `gsettings set org.gnome.shell disable-user-extensions true`.

Output of `journalctl -f`:
```
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: version 14 / git v14-1-g7214544
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: enable(), session mode = user
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _enable()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _enableCloningMouse()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _enableCloningMouse(): using Gnome Shell 3.32 method
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _swapMenu(): Replacing brightness menu item at index 1
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _enableMonitor2ing()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _enableSettingsMonitoring()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _enableScreenshotPatch()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: Extension enabled
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _sync()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _getBrightnessLevel() by proxy = 0.6 <- 60
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _on_brightness_change: current-brightness=0.6, min-brightness=0.05000000000000002
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _startCloningMouse()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlays(0.6, false)
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlays(): enabledMonitors="built-in"
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlays(): skipping run as _monitorNames hasn't been set yet.
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _stopCloningShowMouse()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _stopCloningMouse()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _getBrightnessLevel() by proxy = 0.6 <- 60
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: setSliderValue(0.6) [GS 3.33.90+]
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _sliderChanged(slide, 0.6)
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _storeBrightnessLevel(0.6) by proxy -> 61
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: newDisplayConfig() callback
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _on_monitors_change()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _on_monitors_change(): monitor="eDP-1", connector="eDP-1", index=0
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _getBrightnessLevel() by proxy = 0.61 <- 61
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _on_brightness_change: current-brightness=0.61, min-brightness=0.05000000000000002
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _startCloningMouse()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlays(0.61, true)
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlays(): enabledMonitors="built-in"
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlays(): builtinMonitorName="eDP-1"
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _preventUnredirect(): disabling unredirects, prevent-unredirect=always
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: Create overlay #0: 2560x1440@0,0
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlay(): set opacity 99.45 on overlay #0
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _sync()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _getBrightnessLevel() by proxy = 0.6 <- 60
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _on_brightness_change: current-brightness=0.6, min-brightness=0.05000000000000002
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _startCloningMouse()
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlays(0.6, false)
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _showOverlay(): set opacity 102 on overlay #0
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _getBrightnessLevel() by proxy = 0.6 <- 60
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Soft-Brightness: setSliderValue(0.6) [GS 3.33.90+]
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Sep 23 20:45:16 thinkpadx1 gnome-shell[1152]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: disable(), session mode = user
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _disable()
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _swapMenu(): Replacing brightness menu item at index 1
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _disableMonitor2ing()
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _disableSettingsMonitoring()
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _hideOverlays(): drop overlays, count=1
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _allowUnredirect(): enabling unredirects, prevent-unredirect=always
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _stopCloningShowMouse()
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _stopCloningMouse()
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _disableCloningMouse()
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: _disableScreenshotPatch()
Sep 23 20:45:23 thinkpadx1 gnome-shell[1152]: Soft-Brightness: Extension disabled
` ``

**Comment by F-i-f** [comment]
Thanks for your report.
I'm sorry the extension is giving you trouble.
I've tried reproducing the problem on gnome-shell 3.34 (`gnome-shell-3.34.0-2.fc32`) on Fedora Rawhide (soon-to-be Fedora 32) and the extension works well on this system.

Can you please provide the following information:
- Your distribution (& version) (eg. Ubuntu 1804)
- Your exact gnome-shell version (`rpm -q gnome-shell` or `dpkg -l gnome-shell`)
- Was this an upgrade of the shell or extension, or a fresh install?
- Can you try clearing your dconf database (`dconf reset -f /org/gnome/shell/extensions/soft-brightness/`) and reinstall the extension?
- Is the problem always reproducible?

**Comment by tommy4st** [comment]
Thanks for your reply.

I'm trying to report as much useful information as possible :)

Distribution: Arch Linux; Build ID: rolling
Gnome Versions: (all the latest from the Arch Repository)
gnome-desktop 1:3.34.0-1
gnome-disk-utility 3.34.0-1
gnome-font-viewer 3.34.0-1
gnome-logs 3.34.0-1
gnome-online-accounts 3.34.0-1
gnome-session 3.34.0+2+g9d8b0709-1
gnome-settings-daemon 3.34.0-1
gnome-shell 1:3.34.0+152+g0fdbde910-1
gdm 3.34.0-2

It was a totally fresh install. I tried the clearing you suggested. I even went further an created a complete new user profile, but it didn't work. The shell is working as expected, but I cannot interact with any application except stuff which is added by the shell (like maximize, minimize, close, moving and resizing).

When I switch from Wayland to Xorg, it is actually working as expected. But as Wayland should be the default in Fedora this is not explaining, why it is not working with Gnome on Wayland in Arch.

**Comment by F-i-f** [comment]
Thank you for the testing, you provided the info I was looking for.  I didn't test with Wayland on Fedora 32, just with Xorg.
I'll see what happens with Wayland later and follow up then.
Can you test if the mouse works properly on your set-up with the screen magnifier on?  (Settings > Universal Access > Zoom)
Soft Brightness uses similar code to the Magnifier's when dealing with the mouse, and I'm trying to check if the problem comes from the extension, gnome-shell or Wayland.

**Comment by tommy4st** [comment]
I tested the Magnifier. And it didn't work as I expected. It only accepted clicks, when I clicked a second time without moving the cursor. I would say it's also broken and the main problem originates from upstream. With your extension the second click method didn't work though.

**Comment by F-i-f** [comment]
Thanks for the testing.  
I haven't been able to look into this any further as I've been at work.

But, since Soft Brightness uses the same method for tracking the mouse cursor as the magnifier does, testing the magnifier is a good way to check if the problem comes from Gnome Shell or the extension.
So, it looks like there's a problem with Gnome Shell 3.34  on Wayland.  This isn't a problem with the Soft Brightness extension.

I didn't find a bug for that problem on https://gitlab.gnome.org/GNOME/gnome-shell/issues?scope=all&state=all so I'll do further testing and open one.  I'll also update the GitHub README.md with this information.

**Comment by F-i-f** [comment]
I've [created issue #1719](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1719) on the [Gnome-Shell Gitlab](https://gitlab.gnome.org/GNOME/gnome-shell).

**Comment by F-i-f** [comment]
It's actually a [Mutter](https://gitlab.gnome.org/GNOME/mutter/) issue and is tracked with
+[Mutter issue #826](https://gitlab.gnome.org/GNOME/mutter/issues/826).
Would you mind sharing your mutter version?

**Comment by F-i-f** [comment]
Released version 15 of the extension implements a work-around for that issue.
