### ISSUE TITLE
[feature request] Enable display brightness via DCC

### ISSUE THREAD

**Issue by gsedej** [F-i-f/soft-brightness#7]
Hello!

I found out this interesting applet for adjusting the brightness.
This applet has option to use xrandr gamma brightnes, which is helpfull, but the actuall brightness of monitor does not  change.

The ddcutil offers configuration of the monitor settings, that you would normally have to set via monitor keys. https://www.ddcutil.com/
The ddcui is GUI that also enables setting the monitor brightness via slider.

It would be great if this applet would be able to control actual monitor brightness (via ddcutil)
Ubuntu 18.04 does include ddcutil (cli) which can adjust brightness.

Here is blogpost how to use ddcutil: https://blog.tcharles.fr/ddc-ci-screen-control-on-linux/

(note: I have radeon graphics card with open source driver. I don't know how well it works on intel/nvidia)

**Comment by F-i-f** [comment]
Thank you for the suggestion.
After trying out ddcutil, I'm going to pass using it in Soft-Brightness for now.
My reasons are:
1. ddcutil is not widely available yet.
2. ddcutil needs special set-up: on my systems, dec I2C device nodes are only accessible via root.  Just compiling it (or shipping an executable with the extension) is not enough to enable the feature, some extra udev magic is required to make the correct /dev/i2c device nice
3. Most importantly, brightness changes carried through ddcutil take several seconds to take effect:
   ```shell
   # time ddcutil setvcp 0x10 100
   	0.018 user 2.125 system 58% cpu 3.658 total
   ```
   (0x10 is the feature corresponding to brightness for my Samsung monitor).
4. With my monitor, changing brightness levels with ddcutil also touches other settings.  For example, after experimenting, I wasn't able to reset my monitor to its starting configuration, even after resetting the brightness to its initial setting.  I had to go through a monitor power-cycle.
5. The settings applied by ddcutil are forgotten if the monitor input change.  I was able to reduce the brightness with the right ddcutil command, then switched the monitor to another input.  When I went back to the original input, the brightness was back to its old setting.

While I'm sure [1] and [2] will get addressed as ddcutil gets more widely available, [3] is a real problem, and [4] and [5] are annoying.
Given the nature of I2C I have doubts that [3] can be addressed: I2C will always be slow.

So I will stick to the current alpha layers implementation for now.

**Comment by gsedej** [comment]
Thanks for replying. 
1. ddcutil is available for install in Ubuntu 18.04. Probably also in all distros based on. On Arch, you can install it via AUR. But yes it's not the most present tool in distro.
2. True! But there are some other extensons (CpuFreq) that require user to input password so it enables cpu setting. I do understand implementation burden.
3. I also noticed the lag, but the GUI (ddcui) is very responsive when changing brightness.
4. yes i also tried some "power saving feature" that made me power cycle... 

Is the alpha branch public? I would like to try it (no matter the stability)

**Comment by luetage** [comment]
ddcutil serves another purpose. This extension is an overlay, while ddctuil changes the brightness of the actual screen. Personally I have brightness change over ddcutil enabled as custom script with keyboard shortcuts and I use this extension concurrently to make the screen really dark whenever I need to.

**Comment by F-i-f** [comment]
Have you seen the new [Brightness control using ddcutil](https://extensions.gnome.org/extension/2645/brightness-control-using-ddcutil/) extension?
Closing this issue as there's now a fix with this other extension.

**Comment by gsedej** [comment]
Thank you for sharing info! Also thank you for your extension!
