### ISSUE TITLE
all changes get reverted too 100%

### ISSUE THREAD

**Issue by ente76** [F-i-f/soft-brightness#8]
Hi,

On my HP x360 using your extension has some weird effect:
- I change the gnome slide to approx 20%. The OLED brightness changes immediately to 20%. The brightness slowly goes up to 100%.
- I use the keyboard brightness key to lower brightness. I have to press long / often to make an effect. While I am able to lower the brightness, it immediately goes up again to 100%.

On debug mode I get the following lines:
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _storeBrightnessLevel(0.32) by proxy -> 33
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _sliderChanged(slide, 0.32)
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: setSliderValue(0.32) [GS 3.33.90+]
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _getBrightnessLevel() by proxy = 0.32 <- 32
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _showOverlay(): set opacity 173.39999999999998 on overlay #0
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _showOverlays(0.32, false)
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _startCloningMouse()
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _on_brightness_change: current-brightness=0.32, min-brightness=0.14999999999999997
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _getBrightnessLevel() by proxy = 0.32 <- 32
Dez 13 12:53:01 schlepptop gnome-shell[789]: Soft-Brightness: _sync()
Dez 13 12:53:01 schlepptop pkexec[8332]: ente: Executing command [USER=root] [TTY=unknown] [CWD=/home/ente] [COMMAND=/usr/lib/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.0

It looks like in the last step, you want to store a brightness of 0,32 but you actually store 0,33; this triggers a change on the input value and restarts the process. If I put the slider to 80% I see 21 times the full stack of log lines as above.  The last set of log lines is:
Dez 13 13:04:40 schlepptop gnome-shell[789]: Soft-Brightness: setSliderValue(1) [GS 3.33.90+]
Dez 13 13:04:40 schlepptop gnome-shell[789]: Soft-Brightness: _getBrightnessLevel() by proxy = 1 <- 100
Dez 13 13:04:40 schlepptop gnome-shell[789]: Soft-Brightness: _stopCloningShowMouse(), restoring cursor visibility to true
Dez 13 13:04:40 schlepptop gnome-shell[789]: Soft-Brightness: _on_brightness_change: current-brightness=1, min-brightness=0.14999999999999997
Dez 13 13:04:40 schlepptop gnome-shell[789]: Soft-Brightness: _getBrightnessLevel() by proxy = 1 <- 100
Dez 13 13:04:40 schlepptop gnome-shell[789]: Soft-Brightness: _sync()
Dez 13 13:04:40 schlepptop pkexec[10946]: ente: Executing command [USER=root] [TTY=unknown] [CWD=/home/ente] [COMMAND=/usr/lib/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.>

**Comment by ente76** [comment]
In file extension.js in line 408 remove the +1 and it works like a charm. Tested locally. I guess its less effort if you do the change yourself before I create a commit & push request.

**Comment by rlau89** [comment]
I have installed this via gnome extensions located the file, line and code in question and removed it however the issue still remains. For my case this only happens when I have "Use backlight control" switched on which I would like so that I can use the keyboard shortcuts to control backlight.

**Comment by rlau89** [comment]
Simply needed to log out and back in to restart gnome shell

**Comment by ToniHarri** [comment]
I'm having this same issue. Installed via gnome extensions, and I cannot find the mentioned extension.js file. Where is that located?

**Comment by F-i-f** [comment]
Thank you for the report.
Version 16 has been pushed to http://extensions.gnome.org but it can take a bit for the code to be approved.
In meantime you can get it from the [project homepage](https://github.com/F-i-f/soft-brightness/) or download [version 16 directly here](https://github.com/F-i-f/soft-brightness/releases/download/v16/soft-brightness@fifi.org.v16.shell-extension.zip).
